# Generated by Django 5.2.7 on 2025-12-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variationcategory_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variaton_category',
            new_name='variation_category',
        ),
    ]
